id: P4F788A67
initial_creation_type: input
source_metadata:
  title: Gesar Series
  language: it
  description: 'A series of texts dedicated to the legendary warrior king Gesar (ge
    sar):'
  volume:
    7d9798c70a2d44aab79052988355d133:
      title: Concerning Offering Rites to the Great Lion Gesar
      parent: Commentaries
    7c78794151bb4a65b77c88f2b17558ad:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Guru Yoga
    52740aa39bbf48529e42e440ef8c1257:
      title: Brief Gesar Windhorse Invocation
      parent: Lungta
    bb5b01cefc7b4973b3b793c6eb04aea3:
      title: Short Windhorse Prayer to Gesar
      parent: Lungta
    7696b7d51d9b407bb1a4b3d8ab01652d:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      parent: Offering Rites
    534c5585b91447e0b84b5098a7357c3d:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Prayers
    0c1471182ade4f96a5dcdfc2ee0f3343:
      title: Brief Offering Prayer to Gesar
      parent: Prayers
    4caf1fa147a74e5a9e0e9087230c9317:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Prayers
    000359f33f3c4355b152baeda3edb1a2:
      title: Prayer to Gesar
      parent: Prayers
    da2986bfca9e49809a3fbab2e0ea7b66:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      parent: Prayers
    e8b0ff44fb8c407480b69d440a41c4dd:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      parent: Prayers
    315715f836f24a13bd4d52b16a6cddef:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      parent: Prayers
    2b1a21d35d44441ba6b86b9257d5f5a2:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Sang Offering
created_at: '2022-03-01T03:43:17.454933'
last_modified_at: '2022-03-01T03:43:17.454936'
